In [1]:
import numpy as np
import time

In [2]:
size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2  for x in py_list]
end = time.time()
print(f"time for python list = {end - start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr**2
end = time.time()
print(f"time for np array = {end - start} seconds")


time for python list = 6.8886559009552 seconds
time for np array = 0.057822465896606445 seconds


In [3]:
arr = np.array([1,2,3,4,5])
print(arr ,type(arr) , arr.shape)

arr2 = np.array([1,2,3,4,5,"np"])
print(arr2 ,type(arr2) , arr2.shape)



[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'np'] <class 'numpy.ndarray'> (6,)


In [4]:
arr1 = np.zeros((3,3),dtype="int64")
print(arr1 , arr1.shape)

arr2 = np.ones((3,3),dtype="int64")
print(arr2 , arr2.shape)

arr3 = np.full((3,3),100)
print(arr3 , arr3.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)


In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [6]:
reshapedArr = arr.reshape((3,2))
print(reshapedArr,reshapedArr.shape)

flattened = arr.flatten()
print(flattened ,flattened.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [7]:
arr = np.array([1,2,3,4,5,6,7])

idx = [2,5]
print(arr[idx])
print(arr[arr >2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 6]
[3 4 5 6 7]
[2 4 6]
[1 3 5 7]


In [8]:
#slicing|
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:])
print(arr[:4])
print(arr[3:5])
print(arr[::2])

#[start , end , steps]

[2 3 4 5 6 7]
[1 2 3 4]
[4 5]
[1 3 5 7]


In [9]:
arr = np.array([1,2,3,4,5,6,7])

sub_arr = arr[2:4]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)

print(arr) 


[3 4]
[200   4]
[  1   2 200   4   5   6   7]


In [10]:
# Data types

arr = np.array([1,2,3,4,5,6,7])  #int54
print(arr,arr.dtype)

arr1 = np.array([1,2,3.14,4.5,5,6,7])  #flot64
print(arr1,arr1.dtype)

arr2= np.array([1,2,"hello",{1,3,4}])  #objest
print(arr2,arr2.dtype)

arr3 = np.array([1 + 3j])   #complex128
print(arr3,arr3.dtype)

[1 2 3 4 5 6 7] int64
[1.   2.   3.14 4.5  5.   6.   7.  ] float64
[1 2 'hello' {1, 3, 4}] object
[1.+3.j] complex128


In [11]:
# 2D array

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))

sum_of_col  = np.sum(arr2d ,axis = 0)
print(sum_of_col)

sum_of_row  = np.sum(arr2d ,axis = 1)
print(sum_of_row)

print(arr2d[0:2 , 1:3])  # slicing 2d array 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]]


In [12]:
# 3d array 

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d , arr3d.shape)

# indexing
print(arr3d[1,1,0]) # 9

#slicing 
print(arr3d[0 ,1:,:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[3 4]
 [5 6]]


In [13]:
# vectorization 
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr ** 2)
print(arr + 10) 
print(arr2 ** 3)
print(arr + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 216  343  512  729 1000]
[ 7  9 11 13 15]


In [14]:
#normalisation

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalised_arr = (arr - mean)/std_dev

print(arr , mean , std_dev)

print (normalised_arr,normalised_arr.mean,normalised_arr.std)

[[1 2]
 [3 4]] 2.5 1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]] <built-in method mean of numpy.ndarray object at 0x00000257169F7C30> <built-in method std of numpy.ndarray object at 0x00000257169F7C30>


In [18]:
# aggregate functions

arr =  np.array([1,2,3,4,5])

print(arr)
print(arr.sum())
print(arr.prod())
print(arr.min())
print(arr.max())

print(arr.std())
print(arr.mean())
print(arr.var())


print(arr.argmin())
print(arr.argmax())

[1 2 3 4 5]
15
120
1
5
1.4142135623730951
3.0
2.0
0
4


In [21]:
# power functions

arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]


In [23]:
# log functions
arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
