In [1]:
import numpy as np
import time

In [2]:
size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2  for x in py_list]
end = time.time()
print(f"time for python list = {end - start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr**2
end = time.time()
print(f"time for np array = {end - start} seconds")


time for python list = 7.067659378051758 seconds
time for np array = 0.06050610542297363 seconds


In [3]:
arr = np.array([1,2,3,4,5])
print(arr ,type(arr) , arr.shape)

arr2 = np.array([1,2,3,4,5,"np"])
print(arr2 ,type(arr2) , arr2.shape)



[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'np'] <class 'numpy.ndarray'> (6,)


In [4]:
arr1 = np.zeros((3,3),dtype="int64")
print(arr1 , arr1.shape)

arr2 = np.ones((3,3),dtype="int64")
print(arr2 , arr2.shape)

arr3 = np.full((3,3),100)
print(arr3 , arr3.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)


In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [6]:
reshapedArr = arr.reshape((3,2))
print(reshapedArr,reshapedArr.shape)

flattened = arr.flatten()
print(flattened ,flattened.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [7]:
arr = np.array([1,2,3,4,5,6,7])

idx = [2,5]
print(arr[idx])
print(arr[arr >2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 6]
[3 4 5 6 7]
[2 4 6]
[1 3 5 7]


In [8]:
#slicing|
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:])
print(arr[:4])
print(arr[3:5])
print(arr[::2])

#[start , end , steps]

[2 3 4 5 6 7]
[1 2 3 4]
[4 5]
[1 3 5 7]


In [9]:
arr = np.array([1,2,3,4,5,6,7])

sub_arr = arr[2:4]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)

print(arr) 


[3 4]
[200   4]
[  1   2 200   4   5   6   7]


In [10]:
# Data types

arr = np.array([1,2,3,4,5,6,7])  #int54
print(arr,arr.dtype)

arr1 = np.array([1,2,3.14,4.5,5,6,7])  #flot64
print(arr1,arr1.dtype)

arr2= np.array([1,2,"hello",{1,3,4}])  #objest
print(arr2,arr2.dtype)

arr3 = np.array([1 + 3j])   #complex128
print(arr3,arr3.dtype)

[1 2 3 4 5 6 7] int64
[1.   2.   3.14 4.5  5.   6.   7.  ] float64
[1 2 'hello' {1, 3, 4}] object
[1.+3.j] complex128


In [17]:
# 2D array

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))

sum_of_col  = np.sum(arr2d ,axis = 0)
print(sum_of_col)

sum_of_row  = np.sum(arr2d ,axis = 1)
print(sum_of_row)

print(arr2d[0:2 , 1:3])  # slicing 2d array 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]]


In [21]:
# 3d array 

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d , arr3d.shape)

# indexing
print(arr3d[1,1,0]) # 9

#slicing 
print(arr3d[0 ,1:,:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[3 4]
 [5 6]]
