In [2]:
import numpy as np
import time

In [3]:
size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2  for x in py_list]
end = time.time()
print(f"time for python list = {end - start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr**2
end = time.time()
print(f"time for np array = {end - start} seconds")


time for python list = 7.5908918380737305 seconds
time for np array = 0.07506370544433594 seconds


In [4]:
arr = np.array([1,2,3,4,5])
print(arr ,type(arr) , arr.shape)

arr2 = np.array([1,2,3,4,5,"np"])
print(arr2 ,type(arr2) , arr2.shape)



[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'np'] <class 'numpy.ndarray'> (6,)


In [5]:
arr1 = np.zeros((3,3),dtype="int64")
print(arr1 , arr1.shape)

arr2 = np.ones((3,3),dtype="int64")
print(arr2 , arr2.shape)

arr3 = np.full((3,3),100)
print(arr3 , arr3.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [13]:
reshapedArr = arr.reshape((3,2))
print(reshapedArr,reshapedArr.shape)

flattened = arr.flatten()
print(flattened ,flattened.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [19]:
arr = np.array([1,2,3,4,5,6,7])

idx = [2,5]
print(arr[idx])
print(arr[arr >2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 6]
[3 4 5 6 7]
[2 4 6]
[1 3 5 7]
