In [2]:
import numpy as np

In [4]:
#create from array
arr=np.array([1,2,3,4,5,6])
print(arr,type(arr),arr.shape)

arr2d=np.array([[1,2,3],[4,5,6],[7,9,0]])
print(arr2d,arr2d.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 9 0]] (3, 3)


In [16]:
arr1=np.zeros((3,2),dtype="int")#prefill
print(arr1,arr1.shape)

arr2=np.ones((5),dtype="int")#prefill
print(arr2,arr2.shape)

arr3=np.full((4,3),100)#prefill with value
print(arr3,arr3.shape)

arr4=np.eye(4)#prefill with value
print(arr4,arr4.shape)

arr5=np.arange(2,10,5)
print(arr5)



[[0 0]
 [0 0]
 [0 0]] (3, 2)
[1 1 1 1 1] (5,)
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[2 7]
